dist: xenial
language: python
python: 3.7
services:
- postgresql
install:
- pip install -r requirements/test.txt
before_script:
- psql -c 'create database travis_ci_test;' -U postgres
script:
- py.test --cov-report=xml --cov=instadam tests/
after_success:
- codecov
before_install:
- openssl aes-256-cbc -K $encrypted_7fdaadf61be2_key -iv $encrypted_7fdaadf61be2_iv
  -in deploy_rsa.enc -out deploy_rsa -d
