version: '3.0'
services:
  postgres:
    restart: always
    image: postgres:10
    environment:
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - "dbdata:/var/lib/postgresql/data"
    networks:
      - db_nw
  app:
    restart: always
    build: .
    environment:
      - _DB_USERNAME=${DB_USERNAME}
      - _DB_PASSWORD=${DB_PASSWORD}
      - _DB_NAME=${DB_NAME}
    volumes: 
      - ./instadam:/home/flaskapp/src
    networks:
      - db_nw
      - web_nw
    depends_on:
      - postgres
    entrypoint: ["python","manage.py","deploy"]
  nginx:
    image: "nginx:1.13.5"
    ports:
      - "8080:80"
    volumes:
      - ./conf.d:/etc/nginx/conf.d
    networks:
      - web_nw
    depends_on:
      - app
networks:
  db_nw:
    driver: bridge
  web_nw:
    driver: bridge
volumes:
  dbdata:
