version: '3.0'
services:
  postgres:
    restart: always
    image: postgres:10
    environment:
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - ../postgres-data/postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  app:
    restart: always
    build: .
    environment:
      - _DB_USERNAME=${DB_USERNAME}
      - _DB_PASSWORD=${DB_PASSWORD}
      - _DB_NAME=${DB_NAME}
      - _SECRETE_KEY=${SECRETE_KEY}
    ports:
      - 5000:5000
    volumes: 
      - ../instadam-log:/home/instadam/log
    depends_on:
      - postgres
    command: gunicorn --log-level info --log-file=~/log/gunicorn.log -b 0.0.0.0:5000 wsgi:app
